# Generated by Django 3.0.4 on 2020-03-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200330_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='avarage_ETA',
            field=models.CharField(choices=[('24h', '24 hours'), ('48h', '48 hours'), ('48+', 'more than 48 hours')], default='24h', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('U', 'urgent'), ('L', 'low'), ('H', 'high'), ('N', 'normal')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
