# Generated by Django 3.0.5 on 2020-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200331_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'urgent'), ('Low', 'low'), ('High', 'high'), ('Normal', 'normal')], default='normal', max_length=32),
        ),
    ]
