# Generated by Django 3.0.5 on 2020-04-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, default='undefined', max_length=50, null=True),
        ),
    ]
