# Generated by Django 3.0.5 on 2020-04-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserProfile',
        ),
    ]
