# Generated by Django 3.0.5 on 2020-04-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_customuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
